#!/usr/bin/env bash
set -euo pipefail

# Configuration
if [ -f .env ]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ ! "$line" =~ ^# ]] && [[ "$line" =~ = ]]; then
      export "$line"
    fi
  done < .env
fi
AUDIO_DIR="audio"
VIDEO_DIR="video"
OUTPUT_DIR="output"

AUDIO_FILE="${AUDIO_DIR}/cozy_music.mp3" # No longer used directly, but kept for clarity
BACKGROUND_IMAGE="${VIDEO_DIR}/background.png" # No longer used directly
BASE_VIDEO="${OUTPUT_DIR}/base_1h.mp4"
GENERATED_AUDIO="${OUTPUT_DIR}/generated_audio_theme.mp3"
# GENERATED_VIDEO_THEME="${OUTPUT_DIR}/generated_video_theme.mp4" # This will be generated by generate_video_theme.sh based on AI image

# --- NEW: Path to the AI-generated background image ---
AI_BACKGROUND_IMAGE="/Users/saikiran/.cursor/projects/Users-saikiran-TTT/assets/ai_background_rainy_forest.png"
# --- END NEW ---


# Base duration: 1 hour in seconds, default to 30s for testing if not set
BASE_DURATION_SECONDS="${BASE_VIDEO_DURATION_SECONDS:-30}"

mkdir -p "${AUDIO_DIR}" "${VIDEO_DIR}" "${OUTPUT_DIR}"

echo "[create_base_video] Using FFmpeg version:"
ffmpeg -version | head -n 1 || true

# Generate unique prompt and parameters
echo "[create_base_video] Generating unique prompt..."
eval "$(./scripts/generate_unique_prompt.py)"
echo "[create_base_video] Prompt: ${GENERATED_PROMPT}"
echo "[create_base_video] Computed Theme: ${COMPUTED_THEME}"
echo "[create_base_video] Rain Params: Intensity=${RAIN_INTENSITY}, Wind=${WIND_SPEED}, Color=${COLOR_SHIFT}"

# Use the computed theme
ACTUAL_THEME="${COMPUTED_THEME}"

# --- NEW: Generate a custom AI background for every run ---
echo "[create_base_video] Generating custom AI background for prompt: ${GENERATED_PROMPT}"
TARGET_BG_IMAGE="${OUTPUT_DIR}/ai_background_dynamic.jpg"
if ./venv/bin/python3 ./scripts/generate_ai_image.py "${GENERATED_PROMPT}" "${TARGET_BG_IMAGE}"; then
    echo "[create_base_video] Custom AI background generated successfully."
else
    echo "[create_base_video] WARNING: Custom AI background failed. Falling back to default or color."
    TARGET_BG_IMAGE=""
fi
# --- END NEW ---

echo "[create_base_video] Selected theme: ${ACTUAL_THEME}"
if [[ -n "${TARGET_BG_IMAGE}" ]]; then
    echo "[create_base_video] Using dynamic AI background: ${TARGET_BG_IMAGE}"
else
    echo "[create_base_video] Using FFmpeg generated background (theme color)"
fi

########################################
# 1. Create fresh audio every run (soundscape)
########################################
export DURATION_SECONDS="${BASE_DURATION_SECONDS}"
echo "[create_base_video] Generating new audio soundscape (THEME=${ACTUAL_THEME})..."
export BASE_VIDEO_DURATION_SECONDS="${BASE_DURATION_SECONDS}"
chmod +x "./scripts/generate_soundscape.sh" # Ensure executable
./scripts/generate_soundscape.sh "${GENERATED_AUDIO}" "${ACTUAL_THEME}" # Generate the themed audio

########################################
# 2. Generate video content (TY/APP Logic: Stock -> AI Image Fallback)
########################################
echo "[create_base_video] mode: Realistic Stock/AI Hybrid (TY/APP Logic)"

VIDEO_SUCCESS="false"

# 2.1 Try Pexels Stock Video (Most Realistic)
# We use the GENERATED_PROMPT as the query to get specific visuals (forest, cabin, etc.)
STOCK_QUERY="${GENERATED_PROMPT}"

echo "[create_base_video] Trying Pexels stock video for: ${STOCK_QUERY}"
if ./venv/bin/python3 ./scripts/fetch_stock_video.py "${STOCK_QUERY}" "${OUTPUT_DIR}/stock_background.mp4"; then
    echo "[create_base_video] Stock video downloaded successfully."
    # We use the stock video as the base
    # We force overwrite the theme video to ensure the latest stock is used
    cp -f "${OUTPUT_DIR}/stock_background.mp4" "${OUTPUT_DIR}/generated_video_theme.mp4"
    echo "[create_base_video] Updated generated_video_theme.mp4 with latest stock visuals."
    VIDEO_SUCCESS="true"
else
    echo "[create_base_video] WARNING: Stock video failed. Falling back to AI Image + Synthetic Effects."
fi

# 2.2 Seamless Loop & Overlay (Realistic Visuals Matching Audio)
if [[ "${VIDEO_SUCCESS}" == "true" ]]; then
    echo "[create_base_video] Creating seamless loop of stock video..."
    chmod +x "./scripts/make_seamless_loop.sh"
    # Create a 60s seamless master loop from the source
    ./scripts/make_seamless_loop.sh "${OUTPUT_DIR}/stock_background.mp4" "${OUTPUT_DIR}/seamless_master.mp4" 60
    
    echo "[create_base_video] Layering procedural ${ACTUAL_THEME} effects over stock video..."
    chmod +x "./scripts/generate_video_theme.sh"
    # Ensure the duration is passed
    export DURATION_SECONDS="${BASE_DURATION_SECONDS}"
    ./scripts/generate_video_theme.sh "${OUTPUT_DIR}/generated_video_theme.mp4" "${ACTUAL_THEME}" "${OUTPUT_DIR}/seamless_master.mp4"
    VIDEO_SUCCESS="true"
else
    echo "[create_base_video] Falling back to AI Image + Synthetic Effects."
    chmod +x "./scripts/generate_video_theme.sh"
    export DURATION_SECONDS="${BASE_DURATION_SECONDS}"
    ./scripts/generate_video_theme.sh "${OUTPUT_DIR}/generated_video_theme.mp4" "${ACTUAL_THEME}" "${TARGET_BG_IMAGE}"
    VIDEO_SUCCESS="true"
fi


########################################
# 3. Create 1-hour base video
########################################
echo "[create_base_video] Creating 1-hour base video at 1920x1080 @ 30fps..."

ffmpeg -y \
  -stream_loop -1 \
  -i "${OUTPUT_DIR}/generated_video_theme.mp4" \
  -i "${GENERATED_AUDIO}" \
  -c:v libx264 -preset ultrafast -crf 22 \
  -vf "scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,format=yuv420p" \
  -c:a aac -b:a 128k \
  -t "${BASE_DURATION_SECONDS}" \
  "${BASE_VIDEO}"

echo "[create_base_video] Done. Base video created at: ${BASE_VIDEO}"
